import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// components start

import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ToggleMenuProvider } from "@/contexts/ToggleMenu";

import Header from "@/components/Header/Header";
import { PopupMenu } from "@/components/PopupMenu/PopupMenu";
import BurgerMenu from "@/components/BurgerMenu/BurgerMenu";

// components end

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "the dragon mm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToggleMenuProvider>
            <Header />
            <BurgerMenu />
            <PopupMenu />
            <div className="container">{children}</div>
          </ToggleMenuProvider>
        </UserProvider>
      </body>
    </html>
  );
}
